@startuml
title "Use case - BileMo"
left to right direction

package "BileMo REST API" as api {
    usecase "Login"
    usecase "Get products list" as getProducts
    usecase "Get the details of a product" as getProduct
    usecase "Get registered users linked to a client" as getUsers
    usecase "Get the details of a registered user linked to a client" as getUser
    usecase "Add a new user linked to a client" as addUser
    usecase "Delete a user linked to a client" as deleteUser
}

:Client: -- getProducts
:Client: -- getProduct
:Client: -- getUsers
:Client: -- getUser
:Client: -- addUser
:Client: -- deleteUser
:Client: -- Login

database Database <<system>>
api --- Database

@enduml
