@startuml
title "Use case - BileMo"
left to right direction

package "BileMo REST API" as api {
    usecase "Login"
    usecase "Get products list" as getProducts
    usecase "Get the details of a product" as getProduct
    usecase "Get registered users linked to a customer" as getUsers
    usecase "Get the details of a registered user linked to a customer" as getUser
    usecase "Add a new user linked to a customer" as addUser
    usecase "Delete a user linked to a customer" as deleteUser

    getProducts ...> (Login): include
    getProduct ...> (Login): include
    getUsers ...> (Login): include
    getUser ...> (Login): include
    addUser ...> (Login): include
    deleteUser ...> (Login): include
}

:User: -- getProducts
:User: -- getProduct
:User: -- getUsers
:User: -- getUser
:User: -- addUser
:User: -- deleteUser
:User: -- Login

database Database <<system>>
api --- Database

@enduml
